/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.routis.testpub

class Library {
    // TEST 2
    fun someLibraryMethod(): Boolean {
        return true
    }
}
