/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.routis.testpub

/**
 * A super useful library.
 */
class Library {

    /**
     * What does this method do? Is `true` or is it `false`?
     */
    fun someLibraryMethod(): Boolean = true
}
